version: "3.9"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  web:
    image: sacavid/simple-task:latest
    container_name: "processing"
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge