version: "3.9"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  web:
    build: .
    container_name: "processing"
    restart: on-failure
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "123456"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "users"
      DB_POST: "5432"
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge